# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name': '\u041e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u0435', 'verbose_name_plural': '\u041e\u0431\u043e\u0440\u0443\u0434\u043e\u0432\u0430\u043d\u0438\u0435'},
        ),
    ]
