# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 10, 3, 15, 43, 46, 942947), verbose_name='\u041e\u043f\u0443\u0431\u043b\u0438\u043a\u043e\u0432\u0430\u043d\u0430'),
        ),
    ]
