# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-12 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='description',
            field=models.CharField(db_index=True, max_length=150, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435'),
        ),
    ]
