# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-14 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20180914_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044f'),
        ),
    ]
