# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180914_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header1',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_text',
            field=models.TextField(blank=True, max_length=10000, verbose_name='\u041a\u0440\u0430\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
