# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_odnolineyka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='odnolineyka',
            field=models.FilePathField(path=b'home/c/cn68880/django_1/public_html/media/', verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0443 \u043e\u0434\u043d\u043e\u043b\u0438\u043d\u0435\u0439\u043d\u043e\u0439 \u0441\u0445\u0435\u043c\u044b'),
        ),
    ]
