# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180917_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='odnolineyka',
            new_name='oprosnik',
        ),
    ]
