# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180918_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header2',
            field=models.CharField(blank=True, max_length=500, verbose_name='\u0422\u0435\u0445\u043d\u0438\u0447\u0435\u0441\u043a\u0438\u0435 \u0445\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438'),
        ),
    ]
