# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-18 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_auto_20180918_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageportfolio',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043a \u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f\u043c \u043f\u0440\u0438\u043c\u0435\u0440\u043e\u0432 \u0440\u0430\u0435\u043b\u0438\u0437\u0430\u0446\u0438\u0438'),
        ),
    ]
