# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20180919_0428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertifikat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, max_length=150, verbose_name=' \u0438\u043c\u044f \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u0430')),
                ('image', models.ImageField(blank=True, upload_to=b'', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u0430',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0441\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='struktura',
            field=models.ImageField(default=' ', upload_to=b'', verbose_name='\u0421\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u0430 \u0443\u0441\u043b\u043e\u0432\u043d\u043e\u0433\u043e \u043e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='sertifikat',
            field=models.ManyToManyField(blank=True, to='product.Sertifikat', verbose_name='\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442'),
        ),
    ]
