# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20180919_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sertifikat',
            field=models.ManyToManyField(blank=True, to='product.Sertifikat', verbose_name='\u0421\u0435\u0440\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u044b'),
        ),
    ]
