# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-20 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_product_header_struktura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header_struktura',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a \u0441\u0442\u0440\u0443\u043a\u0442\u0443\u0440\u044b \u0443\u0441\u043b\u043e\u0432\u043d\u043e\u0433\u043e \u043e\u0431\u043e\u0437\u043d\u0430\u0447\u0435\u043d\u0438\u044f'),
        ),
    ]
