# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_category_sertifikat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sertifikat',
        ),
    ]
