# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-21 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180920_1748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularsend',
            options={'verbose_name': '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0443', 'verbose_name_plural': '\u041f\u043e\u0434\u043f\u0438\u0441\u043a\u0438'},
        ),
    ]
